### ISSUE TITLE
Figure 1 generate

### ISSUE THREAD

**Issue by wahrheit-git** [max-andr/relu_networks_overconfident#1]
Can you tell me which scripts did you run to get the specific input partitioning as shown in Figure 1 in the refered paper's code.
The reference's code does not seem to work. If you can share those scripts, it would be great.

**Comment by max-andr** [comment]
Hi,

I attach the code used to create Figure 1. You should run Experiment_2.ipynb.
[geocert_linear_regions_code.zip](https://github.com/max-andr/relu_networks_overconfident/files/3566255/geocert_linear_regions_code.zip)

Let me know if you have some questions.
