### ISSUE TITLE
ReLU as a switch

### ISSUE THREAD

**Issue by ghost** [max-andr/relu_networks_overconfident#2]
When a switch is on 1 volt in gives 1 volt out, n volts in gives n volts out.  
When it is off you get zero volts out.
You can understand ReLU as an on off switch with its own decision making policy.
The weighed sum of a number of weighted sums is still a linear system.
For a particular input with a ReLU neural network the switches (ReLUs) are all in definite states, on or off.  The result is a particular arrangement of weighted sums of weighted sums of....
There is a particular linear projection from a particular input to the output and for inputs in the neighborhood of the input that do not result in any switch changing state.
An ReLU neural network then is a system of switched linear projections.
Since switching happens at zero there are no sudden discontinuities in the output as the input gradually changes.  
For a particular input and a particular output neuron the output is a weighted sum of weighted sums of...  of the input.  This can be converted to a single weighted sum.
You can examine that single weighted sum to see what the networks is looking at in the input.  Or you can calculate some metrics like the angle between the input vector and the weight vector of the single weighted sum.

**Comment by max-andr** [comment]
Hi,

Your intuition sounds correct. 

> You can examine that single weighted sum to see what the networks is looking at in the input. Or you can calculate some metrics like the angle between the input vector and the weight vector of the single weighted sum.

Yes, this kind of analysis is possible to do. Although, as you correctly pointed out, this interpretation of the network would hold only in the neighborhood of the point (a polytope) which has the same ReLU switches.

Do you have some question regarding the paper or the code?

**Comment by ghost** [comment]
The paper and code are on my to-do list.  I'll definitely give it a close read.  
It seems to me there are some weaknesses in the foundations of artificial neural networks.
The weighed sum (dot product) can be used to store <pattern, scalar value> pairs.  You can view it as a linear associative memory.  If you use it to store one association there is very strong error correction due to the central limit theory.  Noise in the input vector elements gets averaged out quite well.  The angle between the input vector and the weight vector is actually zero.
If you use the weighted sum to store 2 associations the angles between the input vectors and the weight vector are not likely to be zero.  That means the vector length of the weight vector must increase to maintain the required scalar responses.   The central limit theorem still applies as normal, however the increase in the vector length of weight vector scales up the amount of Gaussian noise at the output of the weighted sum.

Anyway the interaction of the weighted sum and the central limit theorem seems to be not well known by neural network researchers.


 

    On Thursday, September 26, 2019, 4:03:27 PM GMT+8, Maksym Andriushchenko <notifications@github.com> wrote:  
 
 
Hi,

Your intuition sounds correct.


You can examine that single weighted sum to see what the networks is looking at in the input. Or you can calculate some metrics like the angle between the input vector and the weight vector of the single weighted sum.


Yes, this kind of analysis is possible to do. Although, as you correctly pointed out, this interpretation of the network would hold only in the neighborhood of the point (a polytope) which has the same ReLU switches.

Do you have some question regarding the paper or the code?

**Comment by max-andr** [comment]
> Noise in the input vector elements gets averaged out quite well.

If the noise delta is large enough, then x+delta will be in a different polytope, i.e. the ReLU-switches will be different, and consequently, the weight vector will also be different.

Therefore, I think, if one wants to analyze the robustness of ReLU-networks to random noise, one cannot just deal with a linear classifier (i.e. considering just one weighted sum), but one has to consider the possibility of changing the ReLU-switches after applying the noise. And I think this analysis might be quite complicated.

**Comment by ghost** [comment]
That's true.  However for single layer associative memory the central limit theorem behavior of the weighted sum is very important.  Of course that only matters if you have some use for single layer associative memory.
For example providing a controller deep neural network with external memory, like a Neural Turing Machine.

 

    On Thursday, September 26, 2019, 4:33:09 PM GMT+8, Maksym Andriushchenko <notifications@github.com> wrote:  
 
 

Noise in the input vector elements gets averaged out quite well.


If the noise delta is large enough, then x+delta will be in a different polytope, i.e. the ReLU-switches will be different, and consequently, the weight vector will also be different.

Therefore, I think, if one wants to analyze the robustness of ReLU-networks to random noise, one cannot just deal with a linear classifier (i.e. considering just one weighted sum), but one has to consider the possibility of changing the ReLU-switches after applying the noise. And I think this analysis might be quite complicated.

**Comment by max-andr** [comment]
This is an interesting perspective. But I will close this issue for now since it's not related to the code.

We can continue the discussion via email if you want to share some other ideas.
